name: PR checks
on: pull_request

jobs:
  run-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag etclite-io .
      - name: Run image
        run: |
          docker run -d -p 80:80 etclite-io
          sleep 1 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost

  run-serve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node dependencies
        run: yarn install

      - name: Python dependencies
        run: |
          sudo apt-get update && sudo apt-get install --yes python3-setuptools
          sudo pip3 install -r requirements.txt

      - name: Build assets
        run: |
          yarn build
          PORT=8035 yarn serve &
          sleep 3
          curl --head --fail --retry-delay 5 --retry 10 --retry-connrefused http://localhost:8035

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node dependencies
        run: yarn install

      - name: Python dependencies
        run: sudo pip3 install black flake8

      - name: Lint python
        run: yarn lint-python

  lint-scss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node dependencies
        run: yarn install

      - name: Lint python
        run: yarn lint-scss

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node dependencies
        run: yarn install

      - name: Python dependencies
        run: |
          sudo apt-get update && sudo apt-get install --yes python3-setuptools
          sudo pip3 install -r requirements.txt

      - name: Install coverage
        run: sudo pip3 install coverage

      - name: Test python
        run: |
          coverage run  --source=. -m unittest discover tests
          bash <(curl -s https://codecov.io/bash) -cF python
